"""Initial backend foundation schema

Revision ID: 8356c4da49df
Revises: 
Create Date: 2026-09-01 13:37:08.558094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8356c4da49df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_merchant_id'), 'products', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_foreign_key(None, 'products', 'merchants', ['merchant_id'], ['id'])
    op.drop_column('products', 'frequently_bought_with_ids')
    op.drop_column('products', 'compatible_product_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('compatible_product_ids', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('frequently_bought_with_ids', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_merchant_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    # ### end Alembic commands ###
